import {
    Bell,
    Bot,
    BriefcaseBusiness,
    Cable,
    Database,
    FileClock,
    FileKey,
    FileSliders,
    Flag,
    Gauge,
    KeyRound,
    Library,
    ListChecks,
    Network,
    RefreshCw,
    ScrollText,
    Server,
    Settings,
    ShieldCheck,
    Users,
    Workflow,
    Wrench,
} from "lucide-react";

import type { NavigationItem } from "@/workspaces/navigation";

export const administratorNavigation: NavigationItem[] = [
    {
        section: "Platform",
        id: "system-overview",
        label: "System Overview",
        route: "/administration",
        icon: Gauge,
    },
    {
        section: "Platform",
        id: "platform-health",
        label: "Platform Health",
        route: "/administration/health",
        icon: ShieldCheck,
    },
    {
        section: "Platform",
        id: "services",
        label: "Services",
        route: "/administration/services",
        icon: Server,
    },
    {
        section: "Platform",
        id: "integrations",
        label: "Integrations",
        route: "/administration/integrations",
        icon: Network,
    },
    {
        section: "Administration",
        id: "users",
        label: "Users",
        route: "/administration/users",
        icon: Users,
    },
    {
        section: "Administration",
        id: "roles",
        label: "Roles",
        route: "/administration/roles",
        icon: BriefcaseBusiness,
    },
    {
        section: "Administration",
        id: "permissions",
        label: "Permissions",
        route: "/administration/permissions",
        icon: KeyRound,
    },
    {
        section: "Administration",
        id: "organizations",
        label: "Organizations",
        route: "/administration/organizations",
        icon: Library,
    },
    {
        section: "Data",
        id: "connectors",
        label: "Connectors",
        route: "/administration/connectors",
        icon: Cable,
    },
    {
        section: "Data",
        id: "data-sources",
        label: "Data Sources",
        route: "/administration/data-sources",
        icon: Database,
    },
    {
        section: "Data",
        id: "synchronization",
        label: "Synchronization",
        route: "/administration/synchronization",
        icon: RefreshCw,
    },
    {
        section: "Data",
        id: "import-status",
        label: "Import Status",
        route: "/administration/imports",
        icon: ListChecks,
    },
    {
        section: "Intelligence",
        id: "ai-models",
        label: "AI Models",
        route: "/administration/ai-models",
        icon: Bot,
    },
    {
        section: "Intelligence",
        id: "policies",
        label: "Policies",
        route: "/administration/policies",
        icon: ScrollText,
    },
    {
        section: "Intelligence",
        id: "rules",
        label: "Rules",
        route: "/administration/rules",
        icon: FileSliders,
    },
    {
        section: "Intelligence",
        id: "prompt-library",
        label: "Prompt Library",
        route: "/administration/prompts",
        icon: FileKey,
    },
    {
        section: "Operations",
        id: "audit-log",
        label: "Audit Log",
        route: "/administration/audit-log",
        icon: FileClock,
    },
    {
        section: "Operations",
        id: "background-jobs",
        label: "Background Jobs",
        route: "/administration/jobs",
        icon: Workflow,
    },
    {
        section: "Operations",
        id: "notifications",
        label: "Notifications",
        route: "/administration/notifications",
        icon: Bell,
    },
    {
        section: "Configuration",
        id: "system-settings",
        label: "System Settings",
        route: "/administration/settings",
        icon: Settings,
    },
    {
        section: "Configuration",
        id: "feature-flags",
        label: "Feature Flags",
        route: "/administration/features",
        icon: Flag,
    },
    {
        section: "Configuration",
        id: "licensing",
        label: "Licensing",
        route: "/administration/licensing",
        icon: Wrench,
    },
];
