export type InferenceType =
    | "ATTACK_PATH_EXISTS"
    | "BUSINESS_RISK_INCREASED"
    | "PUBLIC_EXPLOIT_AVAILABLE"
    | "HIGH_LATERAL_MOVEMENT_RISK"
    | "IDENTITY_COMPROMISE_POSSIBLE"
    | "CRITICAL_ASSET_EXPOSED"
    | "ACTIVE_CAMPAIGN_RELATED"
    | "ADDITIONAL_VALIDATION_REQUIRED";
