from dotenv import load_dotenv
import os

load_dotenv()

APP_ENV = os.getenv("APP_ENV")
DEBUG = os.getenv("DEBUG")

WIZ_ENABLED = os.getenv("WIZ_ENABLED")
WIZ_API_URL = os.getenv("WIZ_API_URL")
WIZ_API_TOKEN = os.getenv("WIZ_API_TOKEN")

JIRA_ENABLED = os.getenv("JIRA_ENABLED")
JIRA_URL = os.getenv("JIRA_URL")
JIRA_USER = os.getenv("JIRA_USER")
JIRA_TOKEN = os.getenv("JIRA_TOKEN")

REDIS_ENABLED = os.getenv("REDIS_ENABLED")
REDIS_HOST = os.getenv("REDIS_HOST")
REDIS_PORT = os.getenv("REDIS_PORT")

NEO4J_ENABLED = os.getenv("NEO4J_ENABLED")
NEO4J_URI = os.getenv("NEO4J_URI")
NEO4J_USER = os.getenv("NEO4J_USER")
NEO4J_PASSWORD = os.getenv("NEO4J_PASSWORD")

DEFENDER_ENABLED = os.getenv("DEFENDER_ENABLED")
QRADAR_ENABLED = os.getenv("QRADAR_ENABLED")
CROWDSTRIKE_ENABLED = os.getenv("CROWDSTRIKE_ENABLED")
TENABLE_ENABLED = os.getenv("TENABLE_ENABLED")
QUALYS_ENABLED = os.getenv("QUALYS_ENABLED")
RAPID7_ENABLED = os.getenv("RAPID7_ENABLED")

GREENBONE_REPORT_PATH = os.getenv("GREENBONE_REPORT_PATH")
AI_FINDING_EXPLANATION_ALLOWED_IDS = os.getenv(
    "AI_FINDING_EXPLANATION_ALLOWED_IDS"
)
ASSET_CONTEXT_PATH = os.getenv("ASSET_CONTEXT_PATH")
INCIDENT_CONTEXT_PATH = os.getenv("INCIDENT_CONTEXT_PATH")
HUNT_HYPOTHESIS_REPOSITORY_PATH = os.getenv("HUNT_HYPOTHESIS_REPOSITORY_PATH")

LOCAL_OPERATOR_MODE_ENABLED = os.getenv("LOCAL_OPERATOR_MODE_ENABLED")
LOCAL_OPERATOR_PRINCIPAL_ID = os.getenv("LOCAL_OPERATOR_PRINCIPAL_ID")
LOCAL_OPERATOR_DISPLAY_NAME = os.getenv("LOCAL_OPERATOR_DISPLAY_NAME")
LOCAL_OPERATOR_TOKEN = os.getenv("LOCAL_OPERATOR_TOKEN")
LOCAL_OPERATOR_PERMISSIONS = os.getenv("LOCAL_OPERATOR_PERMISSIONS")
LOCAL_OPERATOR_ALLOWED_ORIGINS = os.getenv("LOCAL_OPERATOR_ALLOWED_ORIGINS")
LOCAL_OPERATOR_SESSION_ENABLED = os.getenv("LOCAL_OPERATOR_SESSION_ENABLED")
LOCAL_OPERATOR_SESSION_LIFETIME_SECONDS = os.getenv(
    "LOCAL_OPERATOR_SESSION_LIFETIME_SECONDS"
)
LOCAL_OPERATOR_SESSION_COOKIE_SECURE = os.getenv(
    "LOCAL_OPERATOR_SESSION_COOKIE_SECURE"
)
LOCAL_OPERATOR_SESSION_COOKIE_NAME = os.getenv("LOCAL_OPERATOR_SESSION_COOKIE_NAME")

OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
OPENAI_FINDING_EXPLANATION_MODEL = os.getenv(
    "OPENAI_FINDING_EXPLANATION_MODEL",
    "gpt-5.6",
)
OPENAI_EXPLANATION_TIMEOUT_SECONDS = os.getenv(
    "OPENAI_EXPLANATION_TIMEOUT_SECONDS",
    "30",
)
AI_MODEL_SELECTION_STATE_PATH = os.getenv(
    "AI_MODEL_SELECTION_STATE_PATH",
    "runtime/ai-model-selection.json",
)
AI_MODEL_SELECTION_AUDIT_PATH = os.getenv(
    "AI_MODEL_SELECTION_AUDIT_PATH",
    "runtime/ai-model-selection-audit.jsonl",
)

NVD_API_KEY = os.getenv("NVD_API_KEY")
NVD_TIMEOUT_SECONDS = os.getenv("NVD_TIMEOUT_SECONDS", "15")

EPSS_TIMEOUT_SECONDS = os.getenv("EPSS_TIMEOUT_SECONDS", "15")

CISA_KEV_TIMEOUT_SECONDS = os.getenv("CISA_KEV_TIMEOUT_SECONDS", "20")
CISA_KEV_CACHE_TTL_SECONDS = os.getenv(
    "CISA_KEV_CACHE_TTL_SECONDS",
    "900",
)
