import {
    BarChart3,
    Briefcase,
    Building2,
    CheckCircle2,
    CircleSlash,
    FileText,
    Gauge,
    Gem,
    ListTodo,
    Shield,
    ShieldAlert,
    TrendingUp,
    Users,
    Workflow,
} from "lucide-react";

import type { NavigationItem } from "@/workspaces/navigation";

export const riskManagerNavigation: NavigationItem[] = [
    {
        section: "Risk Operations",
        id: "risk-overview",
        label: "Risk Overview",
        route: "/risk-management",
        icon: Gauge,
    },
    {
        section: "Risk Operations",
        id: "risk-register",
        label: "Risk Register",
        route: "/risk-management/register",
        icon: ListTodo,
    },
    {
        section: "Risk Operations",
        id: "critical-risks",
        label: "Critical Risks",
        route: "/risk-management/critical",
        icon: ShieldAlert,
    },
    {
        section: "Risk Operations",
        id: "treatment-plans",
        label: "Treatment Plans",
        route: "/risk-management/treatments",
        icon: Workflow,
    },
    {
        section: "Business Context",
        id: "business-services",
        label: "Business Services",
        route: "/risk-management/services",
        icon: Building2,
    },
    {
        section: "Business Context",
        id: "crown-jewels",
        label: "Crown Jewels",
        route: "/risk-management/crown-jewels",
        icon: Gem,
    },
    {
        section: "Business Context",
        id: "business-impact",
        label: "Business Impact",
        route: "/risk-management/impact",
        icon: Briefcase,
    },
    {
        section: "Business Context",
        id: "risk-ownership",
        label: "Risk Ownership",
        route: "/risk-management/ownership",
        icon: Users,
    },
    {
        section: "Governance",
        id: "compliance",
        label: "Compliance",
        route: "/risk-management/compliance",
        icon: Shield,
    },
    {
        section: "Governance",
        id: "exceptions",
        label: "Exceptions",
        route: "/risk-management/exceptions",
        icon: CircleSlash,
    },
    {
        section: "Governance",
        id: "risk-acceptance",
        label: "Risk Acceptance",
        route: "/risk-management/acceptance",
        icon: CheckCircle2,
    },
    {
        section: "Governance",
        id: "policies",
        label: "Policies",
        route: "/risk-management/policies",
        icon: FileText,
    },
    {
        section: "Reporting",
        id: "trends",
        label: "Trends",
        route: "/risk-management/trends",
        icon: TrendingUp,
    },
    {
        section: "Reporting",
        id: "executive-reports",
        label: "Executive Reports",
        route: "/risk-management/reports",
        icon: BarChart3,
    },
];
