import Paper from "@mui/material/Paper";
import Stack from "@mui/material/Stack";
import Typography from "@mui/material/Typography";

import type { DecisionResponse } from "@/types/decision/DecisionResponse";

interface ExecutiveSummaryProps {
    decision: DecisionResponse;
}

export default function ExecutiveSummary({
    decision,
}: ExecutiveSummaryProps) {
    return (
        <Stack spacing={3}>
            <Stack spacing={0.5}>
                <Typography
                    variant="overline"
                    color="primary"
                >
                    Executive Summary
                </Typography>

                <Typography variant="h5">
                    Current Situation
                </Typography>

                <Typography
                    variant="body2"
                    color="text.secondary"
                >
                    High-level assessment generated by the
                    Decision Engine.
                </Typography>
            </Stack>

            <Paper
                variant="outlined"
                sx={{
                    p: 3,
                    borderRadius: 2,
                }}
            >
                <Typography
                    variant="body1"
                    sx={{
                        lineHeight: 1.8,
                    }}
                >
                    {decision.summary}
                </Typography>
            </Paper>

            <Paper
                variant="outlined"
                sx={{
                    p: 3,
                    borderRadius: 2,
                }}
            >
                <Stack spacing={2}>
                    <Typography
                        variant="overline"
                        color="primary"
                    >
                        Executive Assessment
                    </Typography>

                    <Typography
                        variant="body2"
                        color="text.secondary"
                        sx={{
                            lineHeight: 1.8,
                        }}
                    >
                        The Decision Engine correlated technical
                        telemetry, contextual business information
                        and risk indicators to determine the current
                        situation. The recommendation presented in
                        this workspace is supported by evidence,
                        explainable reasoning and estimated business
                        impact.
                    </Typography>
                </Stack>
            </Paper>

            <Paper
                variant="outlined"
                sx={{
                    p: 3,
                    borderRadius: 2,
                }}
            >
                <Stack spacing={1}>
                    <Typography
                        variant="overline"
                        color="primary"
                    >
                        Expected Outcome
                    </Typography>

                    <Typography
                        variant="body2"
                        color="text.secondary"
                    >
                        Executing the recommended response should
                        reduce organizational risk while maintaining
                        transparency, traceability and business
                        continuity.
                    </Typography>
                </Stack>
            </Paper>
        </Stack>
    );
}