"""Deterministic, fail-closed orchestration primitives for the AIDP workflow."""

from .acceptance import AcceptanceHarness, serialize_acceptance_result
from .architect_ingress import ArchitectGitIngress, serialize_architect_ingress_result
from .architect_ingress_acceptance import (
    ArchitectIngressAcceptanceHarness,
    serialize_architect_ingress_acceptance_result,
)
from .architect_writer import (
    ArchitectContractWriter,
    load_architect_task_contract,
    serialize_architect_task_contract,
    serialize_writer_decision,
    serialize_writer_result,
)
from .architect_review import (
    ArchitectReviewCoordinator,
    ProductWorktreeIdentityGuard,
    architect_result_schema,
    create_review_request,
    create_review_result,
    parse_architect_review_result,
    serialize_review_request,
    serialize_review_result,
    validate_review_result,
)

from .contracts import (
    AIDPState,
    AcceptanceResult,
    AcceptanceStatus,
    CleanupStatus,
    ControlPlaneAction,
    ControlPlaneDecision,
    ControlPlaneResult,
    CodexExecutionRequest,
    CodexExecutionResult,
    RunnerResult,
    RunnerStatus,
    ScopeCompliance,
    ValidationResult,
    ReworkContract,
    ArchitectInboxEntry,
    ArchitectTaskContract,
    WriterAction,
    WriterDecision,
    WriterResult,
    WriterControlPlaneAcceptanceResult,
    ConsumptionState,
    ContractInboxItem,
    ConsumptionEvent,
    ReviewEnvelope,
    PublishResult,
    TriggerResult,
    TriggerStatus,
    TriggerPublisherAcceptanceResult,
    WatchIterationEvent,
    WatchRuntimeResult,
    WatchRuntimeStatus,
    IngressStatus,
    ArchitectIngressResult,
    ArchitectIngressAcceptanceResult,
    ArchitectFinding,
    ArchitectReviewDisposition,
    ArchitectReviewProvenance,
    ArchitectReviewRequest,
    ArchitectReviewResult,
    LifecycleResult,
    LifecycleStatus,
    ProductOwnerAcceptanceResult,
    ProductOwnerAcceptanceStatus,
    ProductOwnerApprovalContext,
    ProductOwnerAuthorizationEvidence,
    ProductOwnerDecision,
    ProductOwnerDecisionEvent,
    ProductOwnerDecisionState,
    ProductOwnerOperation,
    AuthenticatedProductOwner,
    ExternalConsistency, ExternalNextTask, ExternalStatusProjectionV1,
    ExternalWatcherHealth, ExternalWatcherOutcome, WatcherHeartbeatV1,
)
from .external_status import ExternalStatusProjector, RepositoryStatusObservation, RuntimeStatusObservation
from .control_plane import (
    AIDPControlPlane,
    LocalArchitectInbox,
    LocalReworkContractStore,
    serialize_architect_inbox_entry,
    serialize_control_plane_decision,
    serialize_control_plane_result,
    serialize_rework_contract,
)
from .executor import (
    CodexExecutionService,
    ExecutionLock,
    GitInspector,
    ProcessOutcome,
    SubprocessRunner,
    serialize_execution_result,
)
from .launcher import CodexLauncher, CodexLauncherError, resolve_codex_launcher
from .repository import AIDPRepository
from .runner import AIDPRunner, serialize_runner_result
from .runtime import LocalRuntimeStore
from .lifecycle import AIDPLifecycleOnce, MAX_AUTONOMOUS_REWORKS
from .lifecycle_projection import LifecycleProjection
from .writer_control_plane_acceptance import (
    WriterControlPlaneAcceptanceHarness,
    serialize_writer_control_plane_acceptance_result,
)
from .trigger_publisher import (
    AIDPWatchOnce,
    ConsumptionStore,
    GitReviewPublisher,
    LocalContractInbox,
    serialize_review_envelope,
    serialize_contract_inbox_item,
    serialize_trigger_result,
)
from .trigger_publisher_acceptance import (
    TriggerPublisherAcceptanceHarness,
    serialize_trigger_publisher_acceptance_result,
)
from .watcher_runtime import (
    AIDPLocalWatcherRuntime,
    DEFAULT_WATCH_INTERVAL_SECONDS,
    MINIMUM_WATCH_INTERVAL_SECONDS,
    WatcherRuntimeLock,
    serialize_watch_iteration_event,
    serialize_watch_runtime_result,
)
from .product_owner_acceptance import ProductOwnerDecisionConsumer, ProductOwnerStatusProjector
from .product_owner_confirmation import (
    ApprovalChallenge,
    ApprovalContextValidator,
    ApprovalContextIssuer,
    ProductOwnerAuthenticator,
    ProductOwnerAuthorizer,
    ProductOwnerConfirmationCommand,
    ProductOwnerConfirmationService,
)
from .product_owner_oidc import (
    KeycloakOIDCClient,
    OIDCError,
    OIDCSessionProof,
    OIDCTransaction,
    OIDCTransport,
    ProductOwnerOIDCConfig,
    ProtectedSecretProvider,
    RequestsOIDCTransport,
    new_oidc_transaction,
)
from .product_owner_web_session import ProductOwnerWebSession, ProductOwnerWebSessionStore
from .product_owner_http import ProductOwnerHTTPApplication

__all__ = [
    "AIDPRepository",
    "AIDPState",
    "AcceptanceHarness",
    "AcceptanceResult",
    "AcceptanceStatus",
    "CleanupStatus",
    "ControlPlaneAction",
    "ControlPlaneDecision",
    "ControlPlaneResult",
    "CodexExecutionRequest",
    "CodexExecutionResult",
    "CodexLauncher",
    "CodexLauncherError",
    "RunnerResult",
    "RunnerStatus",
    "ScopeCompliance",
    "ValidationResult",
    "ReworkContract",
    "ArchitectInboxEntry",
    "ArchitectTaskContract",
    "WriterAction",
    "WriterDecision",
    "WriterResult",
    "WriterControlPlaneAcceptanceResult",
    "ConsumptionState",
    "ContractInboxItem",
    "ConsumptionEvent",
    "ReviewEnvelope",
    "PublishResult",
    "TriggerResult",
    "TriggerStatus",
    "TriggerPublisherAcceptanceResult",
    "WatchIterationEvent",
    "WatchRuntimeResult",
    "WatchRuntimeStatus",
    "IngressStatus",
    "ArchitectIngressResult",
    "ArchitectIngressAcceptanceResult",
    "ArchitectFinding",
    "ArchitectReviewDisposition",
    "ArchitectReviewProvenance",
    "ArchitectReviewRequest",
    "ArchitectReviewResult",
    "ArchitectReviewCoordinator",
    "ProductWorktreeIdentityGuard",
    "LifecycleResult",
    "LifecycleStatus",
    "ProductOwnerAcceptanceResult",
    "ProductOwnerAcceptanceStatus",
    "ProductOwnerApprovalContext",
    "ProductOwnerAuthorizationEvidence",
    "ProductOwnerDecision",
    "ProductOwnerDecisionEvent",
    "ProductOwnerDecisionState",
    "ProductOwnerOperation",
    "AuthenticatedProductOwner",
    "ProductOwnerDecisionConsumer",
    "ProductOwnerStatusProjector",
    "ApprovalChallenge",
    "ApprovalContextValidator",
    "ApprovalContextIssuer",
    "ProductOwnerAuthenticator",
    "ProductOwnerAuthorizer",
    "ProductOwnerConfirmationCommand",
    "ProductOwnerConfirmationService",
    "KeycloakOIDCClient",
    "OIDCError",
    "OIDCSessionProof",
    "OIDCTransaction",
    "OIDCTransport",
    "ProductOwnerOIDCConfig",
    "ProtectedSecretProvider",
    "RequestsOIDCTransport",
    "new_oidc_transaction",
    "ProductOwnerWebSession",
    "ProductOwnerWebSessionStore",
    "ProductOwnerHTTPApplication",
    "AIDPLifecycleOnce",
    "LifecycleProjection",
    "MAX_AUTONOMOUS_REWORKS",
    "architect_result_schema",
    "create_review_request",
    "create_review_result",
    "parse_architect_review_result",
    "serialize_review_request",
    "serialize_review_result",
    "validate_review_result",
    "CodexExecutionService",
    "ExecutionLock",
    "GitInspector",
    "ProcessOutcome",
    "SubprocessRunner",
    "serialize_execution_result",
    "serialize_acceptance_result",
    "AIDPRunner",
    "LocalRuntimeStore",
    "serialize_runner_result",
    "resolve_codex_launcher",
    "AIDPControlPlane",
    "LocalArchitectInbox",
    "LocalReworkContractStore",
    "serialize_architect_inbox_entry",
    "serialize_control_plane_decision",
    "serialize_control_plane_result",
    "serialize_rework_contract",
    "ArchitectContractWriter",
    "load_architect_task_contract",
    "serialize_architect_task_contract",
    "serialize_writer_decision",
    "serialize_writer_result",
    "WriterControlPlaneAcceptanceHarness",
    "serialize_writer_control_plane_acceptance_result",
    "AIDPWatchOnce",
    "ConsumptionStore",
    "GitReviewPublisher",
    "LocalContractInbox",
    "serialize_review_envelope",
    "serialize_contract_inbox_item",
    "serialize_trigger_result",
    "TriggerPublisherAcceptanceHarness",
    "serialize_trigger_publisher_acceptance_result",
    "AIDPLocalWatcherRuntime",
    "DEFAULT_WATCH_INTERVAL_SECONDS",
    "MINIMUM_WATCH_INTERVAL_SECONDS",
    "WatcherRuntimeLock",
    "serialize_watch_iteration_event",
    "serialize_watch_runtime_result",
    "ArchitectGitIngress",
    "serialize_architect_ingress_result",
    "ArchitectIngressAcceptanceHarness",
    "serialize_architect_ingress_acceptance_result",
    "ExternalConsistency", "ExternalNextTask", "ExternalStatusProjectionV1",
    "ExternalWatcherHealth", "ExternalWatcherOutcome", "WatcherHeartbeatV1",
    "ExternalStatusProjector", "RepositoryStatusObservation", "RuntimeStatusObservation",
]
