"""Deterministic, fail-closed orchestration primitives for the AIDP workflow."""

from .acceptance import AcceptanceHarness, serialize_acceptance_result
from .architect_writer import (
    ArchitectContractWriter,
    load_architect_task_contract,
    serialize_architect_task_contract,
    serialize_writer_decision,
    serialize_writer_result,
)

from .contracts import (
    AIDPState,
    AcceptanceResult,
    AcceptanceStatus,
    CleanupStatus,
    ControlPlaneAction,
    ControlPlaneDecision,
    ControlPlaneResult,
    CodexExecutionRequest,
    CodexExecutionResult,
    RunnerResult,
    RunnerStatus,
    ScopeCompliance,
    ValidationResult,
    ReworkContract,
    ArchitectInboxEntry,
    ArchitectTaskContract,
    WriterAction,
    WriterDecision,
    WriterResult,
    WriterControlPlaneAcceptanceResult,
    ConsumptionState,
    ContractInboxItem,
    ConsumptionEvent,
    ReviewEnvelope,
    PublishResult,
    TriggerResult,
    TriggerStatus,
    TriggerPublisherAcceptanceResult,
    WatchIterationEvent,
    WatchRuntimeResult,
    WatchRuntimeStatus,
)
from .control_plane import (
    AIDPControlPlane,
    LocalArchitectInbox,
    LocalReworkContractStore,
    serialize_architect_inbox_entry,
    serialize_control_plane_decision,
    serialize_control_plane_result,
    serialize_rework_contract,
)
from .executor import (
    CodexExecutionService,
    ExecutionLock,
    GitInspector,
    ProcessOutcome,
    SubprocessRunner,
    serialize_execution_result,
)
from .launcher import CodexLauncher, CodexLauncherError, resolve_codex_launcher
from .repository import AIDPRepository
from .runner import AIDPRunner, serialize_runner_result
from .runtime import LocalRuntimeStore
from .writer_control_plane_acceptance import (
    WriterControlPlaneAcceptanceHarness,
    serialize_writer_control_plane_acceptance_result,
)
from .trigger_publisher import (
    AIDPWatchOnce,
    ConsumptionStore,
    GitReviewPublisher,
    LocalContractInbox,
    serialize_review_envelope,
    serialize_trigger_result,
)
from .trigger_publisher_acceptance import (
    TriggerPublisherAcceptanceHarness,
    serialize_trigger_publisher_acceptance_result,
)
from .watcher_runtime import (
    AIDPLocalWatcherRuntime,
    DEFAULT_WATCH_INTERVAL_SECONDS,
    MINIMUM_WATCH_INTERVAL_SECONDS,
    WatcherRuntimeLock,
    serialize_watch_iteration_event,
    serialize_watch_runtime_result,
)

__all__ = [
    "AIDPRepository",
    "AIDPState",
    "AcceptanceHarness",
    "AcceptanceResult",
    "AcceptanceStatus",
    "CleanupStatus",
    "ControlPlaneAction",
    "ControlPlaneDecision",
    "ControlPlaneResult",
    "CodexExecutionRequest",
    "CodexExecutionResult",
    "CodexLauncher",
    "CodexLauncherError",
    "RunnerResult",
    "RunnerStatus",
    "ScopeCompliance",
    "ValidationResult",
    "ReworkContract",
    "ArchitectInboxEntry",
    "ArchitectTaskContract",
    "WriterAction",
    "WriterDecision",
    "WriterResult",
    "WriterControlPlaneAcceptanceResult",
    "ConsumptionState",
    "ContractInboxItem",
    "ConsumptionEvent",
    "ReviewEnvelope",
    "PublishResult",
    "TriggerResult",
    "TriggerStatus",
    "TriggerPublisherAcceptanceResult",
    "WatchIterationEvent",
    "WatchRuntimeResult",
    "WatchRuntimeStatus",
    "CodexExecutionService",
    "ExecutionLock",
    "GitInspector",
    "ProcessOutcome",
    "SubprocessRunner",
    "serialize_execution_result",
    "serialize_acceptance_result",
    "AIDPRunner",
    "LocalRuntimeStore",
    "serialize_runner_result",
    "resolve_codex_launcher",
    "AIDPControlPlane",
    "LocalArchitectInbox",
    "LocalReworkContractStore",
    "serialize_architect_inbox_entry",
    "serialize_control_plane_decision",
    "serialize_control_plane_result",
    "serialize_rework_contract",
    "ArchitectContractWriter",
    "load_architect_task_contract",
    "serialize_architect_task_contract",
    "serialize_writer_decision",
    "serialize_writer_result",
    "WriterControlPlaneAcceptanceHarness",
    "serialize_writer_control_plane_acceptance_result",
    "AIDPWatchOnce",
    "ConsumptionStore",
    "GitReviewPublisher",
    "LocalContractInbox",
    "serialize_review_envelope",
    "serialize_trigger_result",
    "TriggerPublisherAcceptanceHarness",
    "serialize_trigger_publisher_acceptance_result",
    "AIDPLocalWatcherRuntime",
    "DEFAULT_WATCH_INTERVAL_SECONDS",
    "MINIMUM_WATCH_INTERVAL_SECONDS",
    "WatcherRuntimeLock",
    "serialize_watch_iteration_event",
    "serialize_watch_runtime_result",
]
