import {
    Activity,
    BookOpen,
    BugOff,
    Clock3,
    FileSearch,
    FileText,
    LayoutDashboard,
    ListTodo,
    RotateCcw,
    Server,
    Shield,
    ShieldAlert,
    Siren,
    Zap,
} from "lucide-react";

import type { NavigationItem } from "@/workspaces/navigation";

export const incidentResponseNavigation: NavigationItem[] = [
    {
        section: "Incident Operations",
        id: "command-center",
        label: "Command Center",
        route: "/incident-response/incidents/:incidentId/command-center",
        icon: LayoutDashboard,
    },
    {
        section: "Incident Operations",
        id: "overview",
        label: "Overview",
        route: "/incident-response",
        icon: LayoutDashboard,
    },
    {
        section: "Incident Operations",
        id: "active-incidents",
        label: "Active Incidents",
        route: "/incident-response/active",
        icon: Siren,
    },
    {
        section: "Incident Operations",
        id: "incident-queue",
        label: "Incident Queue",
        route: "/incident-response/queue",
        icon: ListTodo,
    },
    {
        section: "Incident Operations",
        id: "major-incidents",
        label: "Major Incidents",
        route: "/incident-response/major",
        icon: ShieldAlert,
    },
    {
        section: "Response",
        id: "containment",
        label: "Containment",
        route: "/incident-response/containment",
        icon: Shield,
    },
    {
        section: "Response",
        id: "eradication",
        label: "Eradication",
        route: "/incident-response/eradication",
        icon: BugOff,
    },
    {
        section: "Response",
        id: "recovery",
        label: "Recovery",
        route: "/incident-response/recovery",
        icon: RotateCcw,
    },
    {
        section: "Response",
        id: "response-actions",
        label: "Response Actions",
        route: "/incident-response/actions",
        icon: Zap,
    },
    {
        section: "Investigation",
        id: "evidence",
        label: "Evidence",
        route: "/incident-response/evidence",
        icon: FileSearch,
    },
    {
        section: "Investigation",
        id: "timeline",
        label: "Timeline",
        route: "/incident-response/timeline",
        icon: Clock3,
    },
    {
        section: "Investigation",
        id: "affected-assets",
        label: "Affected Assets",
        route: "/incident-response/assets",
        icon: Server,
    },
    {
        section: "Investigation",
        id: "impact-analysis",
        label: "Impact Analysis",
        route: "/incident-response/impact",
        icon: Activity,
    },
    {
        section: "Documentation",
        id: "lessons-learned",
        label: "Lessons Learned",
        route: "/incident-response/lessons-learned",
        icon: BookOpen,
    },
    {
        section: "Documentation",
        id: "reports",
        label: "Reports",
        route: "/incident-response/reports",
        icon: FileText,
    },
];
