export enum ActionType {
    ISOLATE_ASSET = "ISOLATE_ASSET",
    PATCH_VULNERABILITY = "PATCH_VULNERABILITY",
    DISABLE_IDENTITY = "DISABLE_IDENTITY",
    ROTATE_CREDENTIALS = "ROTATE_CREDENTIALS",
    BLOCK_INDICATOR = "BLOCK_INDICATOR",
    UPDATE_CONTROL = "UPDATE_CONTROL",
    COLLECT_EVIDENCE = "COLLECT_EVIDENCE",
    THREAT_HUNT = "THREAT_HUNT",
    CREATE_INCIDENT = "CREATE_INCIDENT",
    NOTIFY_OWNER = "NOTIFY_OWNER",
    ACCEPT_RISK = "ACCEPT_RISK",
    REQUEST_EXCEPTION = "REQUEST_EXCEPTION",
}