export enum DecisionType {
    REMEDIATION = "REMEDIATION",
    CONTAINMENT = "CONTAINMENT",
    MITIGATION = "MITIGATION",
    INVESTIGATION = "INVESTIGATION",
    MONITORING = "MONITORING",
    ACCEPTANCE = "ACCEPTANCE",
    EXCEPTION = "EXCEPTION",
    ESCALATION = "ESCALATION",
}