export enum EvidenceType {
    FINDING = "FINDING",
    TELEMETRY = "TELEMETRY",
    THREAT_INTELLIGENCE = "THREAT_INTELLIGENCE",
    VULNERABILITY = "VULNERABILITY",
    ASSET = "ASSET",
    ATTACK_PATH = "ATTACK_PATH",
    IDENTITY = "IDENTITY",
    BUSINESS_CONTEXT = "BUSINESS_CONTEXT",
    ANALYST_NOTE = "ANALYST_NOTE",
}